{
 "title": "Mesos",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Allocator Duration",
   "type": "graph",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    { "expr": "mesos_master_allocation_run_ms" }
   ]
  },
  {
   "title": "Allocation Rate",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "runs/s" }
   ],
   "targets": [
    {
     "expr": "rate(mesos_master_allocation_runs[1m])",
     "legendFormat": "runs/s [1m]"
    }
   ]
  },
  {
   "title": "Frameworks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_master_frameworks_state{state=\"connected_active\"}",
     "legendFormat": "active"
    },
    {
     "expr": "mesos_master_frameworks_state{state=\"connected_inactive\"}",
     "legendFormat": "inactive"
    },
    {
     "expr": "mesos_master_frameworks_state{state=\"disconnected_inactive\"}",
     "legendFormat": "disconnected"
    }
   ]
  },
  {
   "title": "Outstanding Offers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mesos_master_offers_pending", "legendFormat": "outstanding offers" }
   ]
  },
  {
   "title": "Allocator (latency)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_master_allocation_run_latency_ms",
     "legendFormat": "instant"
    }
   ]
  }
 ]
}