{
 "title": "Scheduler Stats",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Launch Groups [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "launches/s" }
   ],
   "targets": [
    { "expr": "operation_launch_group", "legendFormat": "{{dcos_service_name}}" }
   ]
  },
  {
   "title": "Launch Groups [1m] (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "launches/s" }
   ],
   "targets": [
    { "expr": "operation_launch_group", "legendFormat": "{{dcos_service_name}}" }
   ]
  },
  {
   "title": "Offers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(rate(offers_received[1m]))", "legendFormat": "offers_received" },
    {
     "expr": "sum(rate(offers_processed[1m]))",
     "legendFormat": "offers_processed"
    }
   ]
  },
  {
   "title": "Processed Offers [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "offers/s" }
   ],
   "targets": [
    { "expr": "rate(offers_processed[1m])", "legendFormat": "{{dcos_service_name}}" }
   ]
  },
  {
   "title": "Received offers [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "offers/s" }
   ],
   "targets": [
    { "expr": "rate(offers_received[1m])", "legendFormat": "{{dcos_service_name}}" }
   ]
  },
  {
   "title": "Processed Offers [1m](stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "offers/s" }
   ],
   "targets": [
    { "expr": "rate(offers_processed[1m])", "legendFormat": "{{dcos_service_name}}" }
   ]
  },
  {
   "title": "Received offers [1m](stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "offers/s" }
   ],
   "targets": [
    { "expr": "rate(offers_received[1m])", "legendFormat": "{{dcos_service_name}}" }
   ]
  },
  {
   "title": "Revives [1m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(revives[1m])", "legendFormat": "{{dcos_service_name}}" }
   ]
  },
  {
   "title": "Short Declines [1m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "declines_short", "legendFormat": "{{dcos_service_name}}" }
   ]
  },
  {
   "title": "Long Declines [1m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "declines_long", "legendFormat": "{{dcos_service_name}}" }
   ]
  },
  {
   "title": "Revive Throttle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "revives_throttles", "legendFormat": "{{dcos_service_name}}" }
   ]
  },
  {
   "title": "Short Declines [1m] (total)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(declines_short)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Long Declines [1m] (total)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(declines_long)", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}